var lang = {
	"text_0":{"zh":"无标题文档","en":"Untitled document"},
	"text_1":{"zh":"茁壮网络","en":"Robust network"},
	"text_2":{"zh":"总经理办公室","en":"General Manager's Office"},
	"text_3":{"zh":"产品开发","en":"product development"},
	"text_4":{"zh":"WEB开发","en":"WEB development"},
	"text_5":{"zh":"应用开发一组","en":"Application Development Group"},
	"text_6":{"zh":"应用开发二组","en":"Application Development Group II"},
	"text_7":{"zh":"应用开发四组","en":"Four Groups of Application Development"},
	"text_8":{"zh":"应用开发五组","en":"Five Groups of Application Development"},
	"text_9":{"zh":"应用开发六组","en":"Six Groups of Application Development"},
	"text_10":{"zh":"设计工程组","en":"Design Engineering Group"},
	"text_11":{"zh":"分配部门权限失败！","en":"Distribution authority failed!"},
	"text_12":{"zh":"服务器异常！","en":"Server exception!"},
	"text_13":{"zh":"用户和权限不能为空！","en":"Users and privileges can not be empty!"},
	"text_14":{"zh":"获取组织结构失败！","en":"Failed to acquire organizational structure!"},
	"text_15":{"zh":"添加部门","en":"Add Department"},
	"text_16":{"zh":"关闭","en":"Close"},
	"text_17":{"zh":"系统子权限","en":"System Subprivileges"},
	"text_18":{"zh":"系统权限包","en":"System privilege package"},
	"text_19":{"zh":"定","en":"set"},
	"text_20":{"zh":"消","en":"eliminate"},
	"text_21":{"zh":"娱乐圈","en":"Entertainment circle"},
	"text_22":{"zh":"总经理","en":"General manager"},
	"text_23":{"zh":"副总经理","en":"Vice General Manager"},
	"text_24":{"zh":"董事会秘书","en":"Secretary of the Board of Directors"},
	"text_25":{"zh":"总监","en":"Chief inspector"},
	"text_26":{"zh":"经理","en":"manager"},
	"text_27":{"zh":"组长","en":"Group leader"},
	"text_28":{"zh":"员工","en":"staff"},
	"text_29":{"zh":"组","en":"group"},
	"text_30":{"zh":"分配用户权限失败！","en":"Failed to assign user privileges!"},
	"text_31":{"zh":"获取职务列表失败！","en":"Failed to get job list!"},
	"text_32":{"zh":"添加职务","en":"Add duties"},
	"text_33":{"zh":"获取组织结构列表失败！","en":"Failed to get organizational structure list!"},
	"text_34":{"zh":"搜索异常!","en":"Search for exceptions!"},
	"text_35":{"zh":"添加用户","en":"Add user"},
	"text_36":{"zh":"查看部门","en":"Viewing Department"},
	"text_37":{"zh":"编辑部门","en":"Editorial department"},
	"text_38":{"zh":"删除部门","en":"Delete Department"},
	"text_39":{"zh":"移动部门","en":"Mobile sector"},
	"text_40":{"zh":"查看节目权限包","en":"View Program Rights Pack"},
	"text_41":{"zh":"编辑节目权限包","en":"Edit Program Rights Pack"},
	"text_42":{"zh":"设置节目权限包","en":"Setting Program Rights Pack"},
	"text_43":{"zh":"分配权限","en":"Assign authority"},
	"text_44":{"zh":"徐佳宏","en":"Xu Jia Hong"},
	"text_45":{"zh":"李威青","en":"Wei Qing Li"},
	"text_46":{"zh":"曾柯","en":"Zeng Ke"},
	"text_47":{"zh":"增加分类权限","en":"Increase classification authority"},
	"text_48":{"zh":"编辑分类权限","en":"Editorial Category Authority"},
	"text_49":{"zh":"删除分类权限","en":"Delete Category Permissions"},
	"text_50":{"zh":"郭晶","en":"Guo Jing"},
	"text_51":{"zh":"刘文","en":"Liu Wen"},
	"text_52":{"zh":"新建视频权限","en":"New Video Rights"},
	"text_53":{"zh":"查看视频上传状态权限","en":"View Video Upload Status Permissions"},
	"text_54":{"zh":"重置视频上传权限","en":"Reset Video Upload Authority"},
	"text_55":{"zh":"上传视频权限","en":"Upload Video Rights"},
	"text_56":{"zh":"搜索权限","en":"Search Authority"},
	"text_57":{"zh":"编辑视频详情权限","en":"Editing Video Details Rights"},
	"text_58":{"zh":"获取系统权限列表失败！","en":"Failed to get system privilege list!"},
	"text_59":{"zh":"获取系统权限包列表失败！","en":"Failed to get the list of system permission packages!"},
	"text_60":{"zh":"获取系统权限的用户列表失败！","en":"Failed to get user list of system privileges!"},
	"text_61":{"zh":"获取系统权限的部门列表失败！","en":"Failed to get the list of departments with system privileges!"},
	"text_62":{"zh":"获取系统权限的职务列表失败！","en":"Failed to get the job list of system permissions!"},
	"text_63":{"zh":"取消用户权限失败！","en":"Failed to cancel user privileges!"},
	"text_64":{"zh":"取消用户权限包失败！","en":"Failed to cancel user rights package!"},
	"text_65":{"zh":"取消部门权限失败！","en":"Failed to cancel Department authority!"},
	"text_66":{"zh":"取消部门权限包失败！","en":"Failed to cancel departmental privilege package!"},
	"text_67":{"zh":"取消职务权限失败！","en":"Cancellation of post authority failed!"},
	"text_68":{"zh":"取消职务权限包失败！","en":"Failed to cancel the job permission package!"},
	"text_69":{"zh":"后台用户管理系统权限","en":"Background User Management System Rights"},
	"text_70":{"zh":"系统权限","en":"System permissions"},
	"text_71":{"zh":"系统管理员","en":"system administrator"},
	"text_72":{"zh":"针对用户分配权限","en":"Allocation of privileges for users"},
	"text_73":{"zh":"编辑","en":"edit"},
	"text_74":{"zh":"用户列表","en":"User list"},
	"text_75":{"zh":"存","en":"Deposit"},
	"text_76":{"zh":"清空用户","en":"Empty users"},
	"text_77":{"zh":"针对部门分配权限","en":"Distribution of authority to departments"},
	"text_78":{"zh":"部门列表","en":"Departmental list"},
	"text_79":{"zh":"清空部门","en":"Emptying Department"},
	"text_80":{"zh":"针对职务分配权限","en":"Permission to assign duties"},
	"text_81":{"zh":"职务列表","en":"Job list"},
	"text_82":{"zh":"清空职务","en":"Empty duty"},
	"text_83":{"zh":"刘登峰","en":"Deng Feng Liu"},
	"text_84":{"zh":"Web开发","en":"Web development"},
	"text_85":{"zh":"增加用户权限","en":"Increase user privileges"},
	"text_86":{"zh":"编辑用户详情权限","en":"Edit user details permissions"},
	"text_87":{"zh":"搜索用户权限","en":"Search User Rights"},
	"text_88":{"zh":"查看权限包列表权限","en":"View permission package list permissions"},
	"text_89":{"zh":"未知","en":"Unknown"},
	"text_90":{"zh":"用户权限详情","en":"User Rights Details"},
	"text_91":{"zh":"部门权限详情","en":"Details of departmental authority"},
	"text_92":{"zh":"职务权限详情","en":"Details of job authority"},
	"text_93":{"zh":"分配职务权限失败！","en":"Failed to assign authority!"},
	"text_94":{"zh":"分配用户权限包失败！","en":"Failed to allocate user rights package!"},
	"text_95":{"zh":"分配部门权限包失败！","en":"Failed to allocate departmental privilege packages! __________"},
	"text_96":{"zh":"分配职务权限包失败！","en":"Failed to assign job privilege package!"},
	"text_97":{"zh":"获取用户信息失败！","en":"Failed to get user information!"},
	"text_98":{"zh":"获取部门信息失败！","en":"Failed to obtain departmental information!"},
	"text_99":{"zh":"闭","en":"close"},
	"text_100":{"zh":"查看部门列表","en":"View Department List"},
	"text_101":{"zh":"增加部门权限","en":"Increase Department authority"},
	"text_102":{"zh":"编辑部门信息权限","en":"Information Authority of Editorial Department"},
	"text_103":{"zh":"删除部门权限","en":"Delete departmental authority"},
	"text_104":{"zh":"查看部门详情权限","en":"Access to Departmental Details"},
	"text_105":{"zh":"移动部门权限","en":"Mobile Department authority"},
	"text_106":{"zh":"增加职务权限","en":"Increase of post authority"},
	"text_107":{"zh":"编辑职务权限","en":"Editorial authority"},
	"text_108":{"zh":"删除职务权限","en":"Delete post authority"},
	"text_109":{"zh":"查看职务列表权限","en":"View job list permissions"},
	"text_110":{"zh":"查看职务详情权限","en":"Permission to view job details"},
	"text_111":{"zh":"修改密码权限","en":"Modify password permissions"},
	"text_112":{"zh":"创建密码权限","en":"Create password permissions"},
	"text_113":{"zh":"删除用户权限","en":"Delete user privileges"},
	"text_114":{"zh":"查看用户详情权限","en":"Access to View User Details"},
	"text_115":{"zh":"重置密码权限","en":"Reset password permissions"},
	"text_116":{"zh":"查看权限列表权限","en":"View permission list permissions"},
	"text_117":{"zh":"分配权限的权限","en":"Allocation of permissions"},
	"text_118":{"zh":"取消分配权限的权限","en":"Cancel permission to assign permissions"},
	"text_119":{"zh":"复制权限的权限","en":"Permissions to replicate permissions"},
	"text_120":{"zh":"新建权限包权限","en":"New permission package permissions"},
	"text_121":{"zh":"编辑权限包权限","en":"Edit permission package permissions"},
	"text_122":{"zh":"分配权限包权限","en":"Allocate permission package permissions"},
	"text_123":{"zh":"取消分配权限包权限","en":"Cancel Allocation of Permission Packet Permissions"},
	"text_124":{"zh":"删除权限包权限","en":"Delete permission package permissions"},
	"text_125":{"zh":"查看权限包详情权限","en":"View permission package details permissions"},
	"text_126":{"zh":"删除权限包","en":"Delete permission packages"},
	"text_127":{"zh":"获取权限包详情失败！","en":"Failed to obtain permission package details!"},
	"text_128":{"zh":"修改权限包失败！","en":"Failed to modify permission package!"},
	"text_129":{"zh":"权限包名称不能为空！","en":"The permission package name cannot be empty!"},
	"text_130":{"zh":"删除权限包失败！","en":"Delete permission package failed!"},
	"text_131":{"zh":"新建权限包","en":"New permission package"},
	"text_132":{"zh":"权限不能为空！","en":"Permission cannot be empty!"},
	"text_133":{"zh":"新建权限包失败！","en":"New permission package failed!"},
	"text_134":{"zh":"权限包名称","en":"Permission package name"},
	"text_135":{"zh":"确定要清空所有用户吗？","en":"Are you sure you want to clear all users?"},
	"text_136":{"zh":"确定要清空所有部门吗？","en":"Are you sure you want to clear all departments?"},
	"text_137":{"zh":"确定要清空所有职务吗？","en":"Are you sure you want to clear all positions?"},
	"text_138":{"zh":"确定要保存所做修改吗？","en":"Are you sure you want to save the changes?"},
	"text_139":{"zh":"确定要删除所选权限包吗？","en":"Are you sure you want to delete the selected permission package?"},
	"text_140":{"zh":"无","en":"nothing"},
	"text_141":{"zh":"获取权限详情失败！","en":"Failed to obtain permission details!"},
	"text_142":{"zh":"查询部门","en":"Inquiry Department"},
	"text_143":{"zh":"查询权限详情","en":"Details of query permissions"},
	"text_144":{"zh":"删除权限","en":"Delete permission"},
	"text_145":{"zh":"权限包权限","en":"Permission Packet Permissions"},
	"text_146":{"zh":"权限分配","en":"Permission assignment"},
	"text_147":{"zh":"权限包管理","en":"Privilege Packet Management"},
	"text_148":{"zh":"提示信息","en":"Prompt information"},
	"text_149":{"zh":"portal路由系统","en":"Portal Routing System"},
	"text_150":{"zh":"portal管理","en":"Portal Management"},
	"text_151":{"zh":"场景管理","en":"Scenario management"},
	"text_152":{"zh":"系统设置","en":"System setup"},
	"text_153":{"zh":"操作记录","en":"Operation record"},
	"text_154":{"zh":"权限管理","en":"Privilege management"},
	"text_155":{"zh":"我的信息","en":"My message"},
	"text_156":{"zh":"主题","en":"theme"},
	"text_157":{"zh":"关于","en":"about"},
	"text_158":{"zh":"帮助","en":"Help"},
	"text_159":{"zh":"意见反馈","en":"Feedback"},
	"text_160":{"zh":"退出登录","en":"Logout"},
	"text_161":{"zh":"深圳市茁壮网络股份有限公司","en":"Shenzhen Tuanzhuang Network Co., Ltd."},
	"text_162":{"zh":"portal路由管理系统权限","en":"Portal Routing Management System Permissions"},
	"text_163":{"zh":"当前位置：","en":"Current position:"},
	"text_164":{"zh":"服务器请求异常！","en":"Server request exception!"},
	"text_165":{"zh":"原用户令牌错误！请重新登录！","en":"The original user token is wrong! Please login again!"},
	"text_166":{"zh":"原用户令牌过期！请重新登录！","en":"The original user token expires! Please login again!"},
	"text_167":{"zh":"没有权限！","en":"No authority!"},
	"text_168":{"zh":"请求超时","en":"request timeout"},
	"text_169":{"zh":"此分类不可编辑！","en":"This category is not editable!"},
	"text_170":{"zh":"已有提交记录，不能编辑！","en":"The submission record is already available and cannot be edited! ___________"},
	"text_171":{"zh":"此分类已发布！","en":"This classification has been published!"},
	"text_172":{"zh":"当前栏目下已有此分类！","en":"This category already exists under the current column!"},
	"text_173":{"zh":"重复隐藏或还原操作！","en":"Repeat hiding or restoring operations!"},
	"text_174":{"zh":"父类已隐藏，子分类不能隐藏和还原操作！","en":"The parent class is hidden, and the child class cannot hide and restore operations!"},
	"text_175":{"zh":"新建权限包和已存在的重复！","en":"New permission package and existing duplication!"},
	"text_176":{"zh":"未知错误！","en":"Unknown error!"},
	"text_177":{"zh":"年","en":"year"},
	"text_178":{"zh":"月","en":"month"},
	"text_179":{"zh":"日","en":"day"},
	"text_180":{"zh":"时","en":"time"},
	"text_181":{"zh":"分","en":"branch"},
	"text_182":{"zh":"秒","en":"second"},
	"text_183":{"zh":"人工","en":"artificial"},
	"text_184":{"zh":"关联","en":"Relation"},
	"text_185":{"zh":"喜欢","en":"like"},
	"text_186":{"zh":"热播","en":"Hot broadcast"},
	"text_187":{"zh":"热搜","en":"Hot search"},
	"text_188":{"zh":"直播","en":"Live broadcast"},
	"text_189":{"zh":"点播","en":"on demand"},
	"text_190":{"zh":"回看","en":"Look back"},
	"text_191":{"zh":"portal审核","en":"Portal audit"},
	"text_192":{"zh":"portal发布","en":"Portal release"},
	"text_193":{"zh":"优先级设置","en":"Priority Setting"},
	"text_194":{"zh":"查询用户权限失败！","en":"Failed to query user privileges!"},
	"text_195":{"zh":"服务器异常","en":"Server exception"},
	"text_196":{"zh":"注销失败","en":"Logout failure"},
	"text_197":{"zh":"已过期，请重新登录！","en":"It's out of date. Please log in again!"},
	"text_198":{"zh":"首页","en":"home page"},
	"text_199":{"zh":"上一页","en":"Previous page"},
	"text_200":{"zh":"下一页","en":"next page"},
	"text_201":{"zh":"末页","en":"Last"},
	"text_202":{"zh":"页","en":"page"},
	"text_203":{"zh":"操作日志","en":"Operation log"},
	"text_204":{"zh":"查找条件：","en":"Find conditions:"},
	"text_205":{"zh":"操作人：","en":"Operator:"},
	"text_206":{"zh":"时间日期：","en":"Date and time:"},
	"text_207":{"zh":"查找","en":"lookup"},
	"text_208":{"zh":"重置","en":"Reset"},
	"text_209":{"zh":"序号","en":"Serial number"},
	"text_210":{"zh":"操作码","en":"Operation code"},
	"text_211":{"zh":"操作名称","en":"Operation name"},
	"text_212":{"zh":"操作详情","en":"Operation details"},
	"text_213":{"zh":"操作人","en":"Operator"},
	"text_214":{"zh":"操作时间","en":"Operation time"},
	"text_215":{"zh":"操作结果","en":"Operation result"},
	"text_216":{"zh":"结果备注","en":"Result remarks"},
	"text_217":{"zh":"添加成员","en":"Add member"},
	"text_218":{"zh":"型","en":"type"},
	"text_219":{"zh":"添加家庭","en":"Add family"},
	"text_220":{"zh":"加","en":"plus"},
	"text_221":{"zh":"请输入用户的ID或者名称进行添加","en":"Please enter the user's ID or name to add"},
	"text_222":{"zh":"用户ID","en":"User ID"},
	"text_223":{"zh":"用户名","en":"User name"},
	"text_224":{"zh":"昵称","en":"Nickname?"},
	"text_225":{"zh":"地址","en":"address"},
	"text_226":{"zh":"操作","en":"operation"},
	"text_227":{"zh":"请输入家庭的ID进行添加","en":"Please enter the family ID to add it."},
	"text_228":{"zh":"成员已添加","en":"Members have been added"},
	"text_229":{"zh":"家庭已添加","en":"Families have been added"},
	"text_230":{"zh":"成员","en":"member"},
	"text_231":{"zh":"已添加","en":"Added"},
	"text_232":{"zh":"性别","en":"Gender"},
	"text_233":{"zh":"年龄","en":"Age"},
	"text_234":{"zh":"用户不存在","en":"user does not exist"},
	"text_235":{"zh":"搜索无数据","en":"Search for no data"},
	"text_236":{"zh":"新建分组","en":"New grouping"},
	"text_237":{"zh":"称","en":"call"},
	"text_238":{"zh":"情","en":"feeling"},
	"text_239":{"zh":"请输入家庭的ID或者超级用户名进行添加","en":"Please enter the family ID or super username to add"},
	"text_240":{"zh":"男","en":"male"},
	"text_241":{"zh":"女","en":"female"},
	"text_242":{"zh":"强制更新，可被替换","en":"Forced updates, replaceable"},
	"text_243":{"zh":"强制更新，不能替换","en":"Forced updates, not replaceable"},
	"text_244":{"zh":"可被替换","en":"Can be replaced"},
	"text_245":{"zh":"默认portal","en":"Default portal"},
	"text_246":{"zh":"生效时间","en":"entry-into-force time"},
	"text_247":{"zh":"选择默认Portal后原有Portal将被替换","en":"The original Portal will be replaced when the default Portal is selected"},
	"text_248":{"zh":"一","en":"One"},
	"text_249":{"zh":"二","en":"Two"},
	"text_250":{"zh":"三","en":"Three"},
	"text_251":{"zh":"四","en":"Four"},
	"text_252":{"zh":"五","en":"Five"},
	"text_253":{"zh":"六","en":"Six"},
	"text_254":{"zh":"今天","en":"Today"},
	"text_255":{"zh":"清空","en":"empty"},
	"text_256":{"zh":"Y年F","en":"Y F"},
	"text_257":{"zh":"新增portal","en":"Add portal"},
	"text_258":{"zh":"portal类型","en":"Portal type"},
	"text_259":{"zh":"普通版","en":"Ordinary Edition"},
	"text_260":{"zh":"大事件","en":"Big event"},
	"text_261":{"zh":"节日版","en":"Holiday Edition"},
	"text_262":{"zh":"portal名称","en":"Portal name"},
	"text_263":{"zh":"缩略图","en":"thumbnail"},
	"text_264":{"zh":"portal路径","en":"Portal path"},
	"text_265":{"zh":"终端类型","en":"Terminal type"},
	"text_266":{"zh":"全部","en":"whole"},
	"text_267":{"zh":"机顶盒","en":"Set top box"},
	"text_268":{"zh":"CA卡","en":"CA card"},
	"text_269":{"zh":"手机","en":"Mobile phone"},
	"text_270":{"zh":"电脑","en":"Computer"},
	"text_271":{"zh":"系统类型","en":"System type"},
	"text_272":{"zh":"安卓缩略图url","en":"Android thumbnail URL"},
	"text_273":{"zh":"描述","en":"describe"},
	"text_274":{"zh":"服务器异常!","en":"Server exception!"},
	"text_275":{"zh":"portal名称不能为空！","en":"Portal name cannot be empty!"},
	"text_276":{"zh":"portal路径不能为空！","en":"The portal path cannot be empty!"},
	"text_277":{"zh":"portal路径错误！","en":"Portal path error!"},
	"text_278":{"zh":"请填写portal缩略图","en":"Please fill in the portal thumbnail"},
	"text_279":{"zh":"内容包含敏感词！","en":"Content contains sensitive words!"},
	"text_280":{"zh":"此处为通过配置文件修改,若只改名称或描述，则忽略不填","en":"Here is to modify it through configuration file. If you only change the name or description, ignore not filling in."},
	"text_281":{"zh":"portal缩略图","en":"Portal thumbnails"},
	"text_282":{"zh":"若只改名称或描述，则忽略不填","en":"If you change the name or description only, ignore not to fill in"},
	"text_283":{"zh":"Portal风格","en":"Portal style"},
	"text_284":{"zh":"保存","en":"Preservation"},
	"text_285":{"zh":"新增风格","en":"New style"},
	"text_286":{"zh":"风格名称:","en":"Style Name:"},
	"text_287":{"zh":"请输入风格名称","en":"Please enter a style name"},
	"text_288":{"zh":"风格地址:","en":"Style Address:"},
	"text_289":{"zh":"请输入风格地址","en":"Please enter a style address"},
	"text_290":{"zh":"用户属性版","en":"User Attribute Edition"},
	"text_291":{"zh":"大事件版","en":"Big event Edition"},
	"text_292":{"zh":"有操作还没有保完成，请完成之后再新增","en":"The operation is not guaranteed. Please add it after completion."},
	"text_293":{"zh":"预览","en":"preview"},
	"text_294":{"zh":"删除","en":"delete"},
	"text_295":{"zh":"风格名称不能为空!","en":"Style name can not be empty!"},
	"text_296":{"zh":"风格地址不能为空!","en":"Style address can not be empty!"},
	"text_297":{"zh":"请输入风格缩略图URL!","en":"Please enter the style thumbnail URL!"},
	"text_298":{"zh":"有没有保存的操作，请保存后再确定","en":"Do you have any saving operation? Please save it and confirm it later."},
	"text_299":{"zh":"portal名称错误！","en":"Portal name error!"},
	"text_300":{"zh":"请输入portalurl","en":"Please enter portalurl"},
	"text_301":{"zh":"用户组管理","en":"User Group Management"},
	"text_302":{"zh":"查看成员","en":"View members"},
	"text_303":{"zh":"删除组","en":"delete group"},
	"text_304":{"zh":"导入用户组","en":"Import user groups"},
	"text_305":{"zh":"组名称","en":"Group name"},
	"text_306":{"zh":"组信息","en":"Group information"},
	"text_307":{"zh":"输入您要搜索的用户组名","en":"Enter the user group name you want to search for"},
	"text_308":{"zh":"portal列表","en":"Portal list"},
	"text_309":{"zh":"Linux路由列表","en":"Linux Routing List"},
	"text_310":{"zh":"android路由列表","en":"Android Routing List"},
	"text_311":{"zh":"portal设置","en":"Portal settings"},
	"text_312":{"zh":"区域分组","en":"Area grouping"},
	"text_313":{"zh":"自定义分组","en":"Custom Grouping"},
	"text_314":{"zh":"portal名称：","en":"Portal name:"},
	"text_315":{"zh":"终端类型：","en":"Terminal type:"},
	"text_316":{"zh":"系统类型：","en":"System type:"},
	"text_317":{"zh":"portal描述：","en":"Portal description:"},
	"text_318":{"zh":"portal地址：","en":"Portal address:"},
	"text_319":{"zh":"略缩图地址：","en":"Sketch address:"},
	"text_320":{"zh":"创建时间：","en":"Creation time:"},
	"text_321":{"zh":"最近修改时间：","en":"Latest revision time:"},
	"text_322":{"zh":"无菜单风格","en":"Menu-Free Style"},
	"text_323":{"zh":"深灰色","en":"Dark grey"},
	"text_324":{"zh":"儿童绿","en":"Children's green"},
	"text_325":{"zh":"深海蓝","en":"Deep sea blue"},
	"text_326":{"zh":"浪漫紫","en":"Romantic purple"},
	"text_327":{"zh":"T型portal","en":"T portal"},
	"text_328":{"zh":"T风格菜单","en":"T-style menu"},
	"text_329":{"zh":"广告版","en":"Advertising version"},
	"text_330":{"zh":"右上推荐版","en":"Upper right recommended Edition"},
	"text_331":{"zh":"左上推荐版","en":"Top left recommended Edition"},
	"text_332":{"zh":"左侧推荐版","en":"Left Recommended Edition"},
	"text_333":{"zh":"新版portal","en":"New version of portal"},
	"text_334":{"zh":"大连天猫portal","en":"Dalian Tianmao Portal"},
	"text_335":{"zh":"开启大事件","en":"Open Big Events"},
	"text_336":{"zh":"开启","en":"open"},
	"text_337":{"zh":"开启成功","en":"Successful opening"},
	"text_338":{"zh":"开启失败","en":"Open failure"},
	"text_339":{"zh":"取消","en":"cancel"},
	"text_340":{"zh":"下一步","en":"Next step"},
	"text_341":{"zh":"分组名不能为空！","en":"Group name cannot be empty!"},
	"text_342":{"zh":"没有权限，无法添加成员","en":"No permission to add members"},
	"text_343":{"zh":"没有权限，无法删除用户组","en":"No permission to delete user groups"},
	"text_344":{"zh":"确定删除用户组吗？","en":"Are you sure you want to delete user groups?"},
	"text_345":{"zh":"确定要删除所选组吗？","en":"Are you sure you want to delete the selected group?"},
	"text_346":{"zh":"确定","en":"Determine"},
	"text_347":{"zh":"没有找到您要搜索的分组","en":"No grouping was found for you to search for"},
	"text_348":{"zh":"默认分组","en":"Default grouping"},
	"text_349":{"zh":"节日","en":"festival"},
	"text_350":{"zh":"用户组：","en":"User group:"},
	"text_351":{"zh":"生效时间：","en":"Effective time:"},
	"text_352":{"zh":"结束时间：","en":"Ending time:"},
	"text_353":{"zh":"类型：","en":"Type:"},
	"text_354":{"zh":"获取已开启大事件详情失败","en":"Failed to retrieve details of major events that have been opened"},
	"text_355":{"zh":"获取开启大事件详情失败","en":"Failed to retrieve details for opening major events"},
	"text_356":{"zh":"没有权限，无法添加用户组","en":"No permission to add user groups"},
	"text_357":{"zh":"用户组名已存在","en":"User group name already exists"},
	"text_358":{"zh":"没有权限，无法删除","en":"No permission to delete"},
	"text_359":{"zh":"分组存在成员，无法删除","en":"Groups have members and cannot be deleted"},
	"text_360":{"zh":"添加成员成功","en":"Successful addition of members"},
	"text_361":{"zh":"没有权限，无法添加用户","en":"No permission to add users"},
	"text_362":{"zh":"该用户已经存在于用户组","en":"The user already exists in the user group"},
	"text_363":{"zh":"没有权限，无法删除成员","en":"No permission to delete members"},
	"text_364":{"zh":"提交","en":"Submission"},
	"text_365":{"zh":"请选择成员","en":"Please select members"},
	"text_366":{"zh":"选择默认portal","en":"Select the default portal"},
	"text_367":{"zh":"未设置portal！","en":"Portal is not set!"},
	"text_368":{"zh":"上一步","en":"Previous step"},
	"text_369":{"zh":"请求数据失败！","en":"Failed to request data!"},
	"text_370":{"zh":"portal已存在，无法添加","en":"Portal already exists and cannot be added"},
	"text_371":{"zh":"portal已生效，不可删除","en":"Portal is in effect and cannot be deleted"},
	"text_372":{"zh":"portal已生效，不能编辑","en":"Portal is in effect and cannot be edited"},
	"text_373":{"zh":"默认portal不能取消","en":"Default portal cannot be cancelled"},
	"text_374":{"zh":"未获取当前区域列表！","en":"Not getting the current region list!"},
	"text_375":{"zh":"编辑portal","en":"Edit portal"},
	"text_376":{"zh":"设置的时间小于当前时间，关联之后将立即生效","en":"Setting time is less than the current time, the association will take effect immediately"},
	"text_377":{"zh":"确定要取消所选Portal关联吗？","en":"Are you sure you want to cancel the selected Portal association?"},
	"text_378":{"zh":"portal详情","en":"Portal details"},
	"text_379":{"zh":"没有权限，无法编辑","en":"No permissions, no editing"},
	"text_380":{"zh":"个性portal不能编辑","en":"Personality portal cannot be edited"},
	"text_381":{"zh":"个","en":"individual"},
	"text_382":{"zh":"启用大事件","en":"Enabling Big Events"},
	"text_383":{"zh":"请选择用户组","en":"Select User Groups"},
	"text_384":{"zh":"失效时间：","en":"Failure time:"},
	"text_385":{"zh":"大事件：","en":"Big events:"},
	"text_386":{"zh":"节日：","en":"Festivals:"},
	"text_387":{"zh":"请选择开始时间","en":"Please choose the start time."},
	"text_388":{"zh":"请选择结束时间","en":"Please choose the end time."},
	"text_389":{"zh":"portal属性：","en":"Portal property:"},
	"text_390":{"zh":"预览portal","en":"Preview portal"},
	"text_391":{"zh":"详情","en":"details"},
	"text_392":{"zh":"取消关联","en":"Cancel Association"},
	"text_393":{"zh":"分页","en":"paging"},
	"text_394":{"zh":"修改","en":"modify"},
	"text_395":{"zh":"没有相关类型路由！","en":"There are no related types of routing!"},
	"text_396":{"zh":"认","en":"recognize"},
	"text_397":{"zh":"修改portal","en":"Modify portal"},
	"text_398":{"zh":"确定要删除所选portal吗？","en":"Are you sure you want to delete the selected portal?"},
	"text_399":{"zh":"删除失败：","en":"Delete failed:"},
	"text_400":{"zh":"该portal已被用户组关联！","en":"The portal has been associated with user groups!"},
	"text_401":{"zh":"删除成功","en":"Delete successful"},
	"text_402":{"zh":"个,失败","en":"Fail"},
	"text_403":{"zh":"个!","en":"One!"},
	"text_404":{"zh":"返回自定义分组","en":"Return custom grouping"},
	"text_405":{"zh":"用户组列表","en":"User Group List"},
	"text_406":{"zh":"预览图","en":"low source"},
	"text_407":{"zh":"是否可以替换","en":"Is it replaceable?"},
	"text_408":{"zh":"是","en":"yes"},
	"text_409":{"zh":"否","en":"no"},
	"text_410":{"zh":"查找成员:","en":"Find members:"},
	"text_411":{"zh":"请输入用户ID或名称查找","en":"Please enter user ID or name to find"},
	"text_412":{"zh":"用户id","en":"User ID"},
	"text_413":{"zh":"成员不存在","en":"Membership does not exist"},
	"text_414":{"zh":"查看所在用户组","en":"View the user group"},
	"text_415":{"zh":"所在用户组：","en":"User Group:"},
	"text_416":{"zh":"该分组暂无成员","en":"The group has no members at present."},
	"text_417":{"zh":"家庭id","en":"Family ID"},
	"text_418":{"zh":"家庭名","en":"Family name"},
	"text_419":{"zh":"管理员名","en":"Administrator name"},
	"text_420":{"zh":"添加","en":"Add to"},
	"text_421":{"zh":"删除确认","en":"Delete confirm"},
	"text_422":{"zh":"删除选中配置？","en":"Delete the selected configuration?"},
	"text_423":{"zh":"型号:","en":"Model:"},
	"text_424":{"zh":"请输入终端型号","en":"Please enter the terminal model"},
	"text_425":{"zh":"请输入RCID","en":"Please enter RCID"},
	"text_426":{"zh":"BIN地址:","en":"BIN address:"},
	"text_427":{"zh":"请输入BIN地址","en":"Please enter BIN address"},
	"text_428":{"zh":"新增","en":"Newly added"},
	"text_429":{"zh":"键值配置","en":"Key value configuration"},
	"text_430":{"zh":"请输入CODEID","en":"Please enter CODEID"},
	"text_431":{"zh":"值","en":"value"},
	"text_432":{"zh":"请输入BIN文件地址","en":"Please enter the BIN file address"},
	"text_433":{"zh":"修改成功","en":"Modified success"},
	"text_434":{"zh":"添加成功","en":"Add success"},
	"text_435":{"zh":"修改失败","en":"Modification failed"},
	"text_436":{"zh":"添加失败","en":"Add failure"},
	"text_437":{"zh":"BIN文件验证","en":"BIN File Verification"},
	"text_438":{"zh":"文件，是否继续添加？","en":"Does the file continue to be added?"},
	"text_439":{"zh":"获取列表失败","en":"Failed to retrieve list"},
	"text_440":{"zh":"合作方ID","en":"Partner ID"},
	"text_441":{"zh":"合作方名称","en":"Name of partner"},
	"text_442":{"zh":"合作方类型","en":"Types of partners"},
	"text_443":{"zh":"频道ID","en":"Channel ID"},
	"text_444":{"zh":"频道名称","en":"Channel name"},
	"text_445":{"zh":"类型ID","en":"Type ID"},
	"text_446":{"zh":"类型名称","en":"Type name"},
	"text_447":{"zh":"排序","en":"sort"},
	"text_448":{"zh":"保存成功!","en":"Save successfully!"},
	"text_449":{"zh":"保存失败","en":"Save failed"},
	"text_450":{"zh":"隐藏","en":"hide"},
	"text_451":{"zh":"按键管理","en":"Key management"},
	"text_452":{"zh":"型号","en":"Model"},
	"text_453":{"zh":"地址路径","en":"Address path"},
	"text_454":{"zh":"优先级","en":"priority"},
	"text_455":{"zh":"类型","en":"type"},
	"text_456":{"zh":"频道","en":"channel"},
	"text_457":{"zh":"终端按键","en":"Terminal button"},
	"text_458":{"zh":"优先级列表","en":"Priority List"},
	"text_459":{"zh":"筛选","en":"screen"},
	"text_460":{"zh":"自定义","en":"custom"},
	"text_461":{"zh":"输入您要搜索的导演姓名","en":"Enter the name of the director you want to search for"},
	"text_462":{"zh":"输入您要搜索的演员姓名","en":"Enter the name of the actor you want to search for"},
	"text_463":{"zh":"自定义：","en":"Customization:"},
	"text_464":{"zh":"单集","en":"Single set"},
	"text_465":{"zh":"内容类型","en":"Content type"},
	"text_466":{"zh":"电影","en":"Film"},
	"text_467":{"zh":"电视剧","en":"TV play"},
	"text_468":{"zh":"综艺","en":"Variety"},
	"text_469":{"zh":"体育","en":"Sports"},
	"text_470":{"zh":"资讯","en":"information"},
	"text_471":{"zh":"音乐","en":"Music"},
	"text_472":{"zh":"教育","en":"education"},
	"text_473":{"zh":"生活","en":"Life"},
	"text_474":{"zh":"场景复制插件","en":"Scenario Replication Plug-in"},
	"text_475":{"zh":".选中portal","en":"Select portal"},
	"text_476":{"zh":".选中场景","en":"Select scenarios"},
	"text_477":{"zh":"list初始化为空","en":"List initialized to empty"},
	"text_478":{"zh":"选择复制场景","en":"Select the replication scenario"},
	"text_479":{"zh":"已达到上限","en":"The ceiling has been reached."},
	"text_480":{"zh":"设置","en":"Set up"},
	"text_481":{"zh":"无要求","en":"No requirement"},
	"text_482":{"zh":"提交成功!","en":"Successful submission!"},
	"text_483":{"zh":"详情编辑","en":"Details editor"},
	"text_484":{"zh":"删除失败","en":"Delete failed"},
	"text_485":{"zh":"场景关联删除","en":"Scenario Association deletion"},
	"text_486":{"zh":"你确定要删除以下场景?","en":"Are you sure you want to delete the following scenarios?"},
	"text_487":{"zh":"确定要删除当前推荐吗？","en":"Are you sure you want to delete the current recommendation?"},
	"text_488":{"zh":"媒资类型","en":"Media capital type"},
	"text_489":{"zh":"子类型","en":"Subtype"},
	"text_490":{"zh":"源类型","en":"Source type"},
	"text_491":{"zh":"应用","en":"application"},
	"text_492":{"zh":"单曲","en":"single"},
	"text_493":{"zh":"歌手","en":"singer"},
	"text_494":{"zh":"专辑","en":"Album"},
	"text_495":{"zh":"新闻","en":"Journalism"},
	"text_496":{"zh":"监控频道","en":"Monitoring channel"},
	"text_497":{"zh":"马赛克","en":"Mosaic"},
	"text_498":{"zh":"路线出行","en":"Route trip"},
	"text_499":{"zh":"电商活动","en":"Electricity supplier activities"},
	"text_500":{"zh":"电商商品","en":"Electronic commerce commodity"},
	"text_501":{"zh":"电商商铺","en":"Electricity supplier shops"},
	"text_502":{"zh":"景点门票","en":"Tickets for scenic spots"},
	"text_503":{"zh":"酒店住宿","en":"Hotel accommodation"},
	"text_504":{"zh":"专题","en":"special"},
	"text_505":{"zh":"直播间","en":"Direct seeding room"},
	"text_506":{"zh":"播单","en":"Broadcast sheet"},
	"text_507":{"zh":"直播间回看","en":"Look back at the live broadcaster"},
	"text_508":{"zh":"提供商","en":"provider"},
	"text_509":{"zh":"地区","en":"region"},
	"text_510":{"zh":"内地","en":"Inland"},
	"text_511":{"zh":"港台","en":"Hong Kong and Taiwan"},
	"text_512":{"zh":"美国","en":"U.S.A"},
	"text_513":{"zh":"英国","en":"Britain"},
	"text_514":{"zh":"韩国","en":"The Republic of Korea"},
	"text_515":{"zh":"法国","en":"France"},
	"text_516":{"zh":"日本","en":"Japan"},
	"text_517":{"zh":"印度","en":"India"},
	"text_518":{"zh":"德国","en":"Germany"},
	"text_519":{"zh":"芬兰","en":"Finland"},
	"text_520":{"zh":"意大利","en":"Italy"},
	"text_521":{"zh":"丹麦","en":"Denmark"},
	"text_522":{"zh":"其他","en":"Other"},
	"text_523":{"zh":"上传人","en":"Uploading people"},
	"text_524":{"zh":"上传时间","en":"Upload time"},
	"text_525":{"zh":"近一天","en":"Nearly one day"},
	"text_526":{"zh":"近一周","en":"Nearly a week"},
	"text_527":{"zh":"近两周","en":"Nearly two weeks"},
	"text_528":{"zh":"近一月","en":"Nearly one month"},
	"text_529":{"zh":"近三月","en":"Near March"},
	"text_530":{"zh":"近半年","en":"Nearly half a year"},
	"text_531":{"zh":"发布时间","en":"Release time"},
	"text_532":{"zh":"近一小时","en":"Nearly one hour"},
	"text_533":{"zh":"语言","en":"language"},
	"text_534":{"zh":"普通话","en":"Mandarin"},
	"text_535":{"zh":"粤语","en":"Cantonese"},
	"text_536":{"zh":"英语","en":"English?"},
	"text_537":{"zh":"德语","en":"German"},
	"text_538":{"zh":"法语","en":"French"},
	"text_539":{"zh":"俄语","en":"Russian"},
	"text_540":{"zh":"韩语","en":"Korean"},
	"text_541":{"zh":"日语","en":"Japanese"},
	"text_542":{"zh":"意大利语","en":"Italian"},
	"text_543":{"zh":"西班牙语","en":"Spanish"},
	"text_544":{"zh":"导演","en":"director"},
	"text_545":{"zh":"陈凯歌","en":"Kaige Chen"},
	"text_546":{"zh":"徐克","en":"Tsui Hark"},
	"text_547":{"zh":"冯小刚","en":"Feng Xiaogang"},
	"text_548":{"zh":"王晶","en":"Jing Wong"},
	"text_549":{"zh":"张艺谋","en":"Zhang Yimou"},
	"text_550":{"zh":"李安","en":"Ang Lee"},
	"text_551":{"zh":"演员","en":"performer"},
	"text_552":{"zh":"高圆圆","en":"Gao Yuanyuan"},
	"text_553":{"zh":"李易峰","en":"Li Yifeng"},
	"text_554":{"zh":"邓超","en":"Deng Chao"},
	"text_555":{"zh":"孙俪","en":"Sun Li"},
	"text_556":{"zh":"范冰冰","en":"Fan Bingbing"},
	"text_557":{"zh":"胡歌","en":"Hu Ge"},
	"text_558":{"zh":"云游戏","en":"Cloud games"},
	"text_559":{"zh":"自办频道","en":"Self channel"},
	"text_560":{"zh":"明星百科","en":"Star Encyclopedia"},
	"text_561":{"zh":"回看虚拟ID","en":"Look back at the virtual ID"},
	"text_562":{"zh":"商家","en":"business"},
	"text_563":{"zh":"活动","en":"activity"},
	"text_564":{"zh":"商品","en":"commodity"},
	"text_565":{"zh":"路线产品","en":"Route product"},
	"text_566":{"zh":"新建场景","en":"New scene"},
	"text_567":{"zh":"复制已有场景","en":"Replicate existing scenarios"},
	"text_568":{"zh":"名称:","en":"Name:"},
	"text_569":{"zh":"场景内容:","en":"Scene content:"},
	"text_570":{"zh":"要求:","en":"Requirement:"},
	"text_571":{"zh":"放弃","en":"give up"},
	"text_572":{"zh":"基础信息","en":"Basic information"},
	"text_573":{"zh":"数据控制","en":"Data control"},
	"text_574":{"zh":"设置后,双击单元格添加节目","en":"After setting, double-click the cell to add the program"},
	"text_575":{"zh":"场景名称：","en":"Scenario Name:"},
	"text_576":{"zh":"场景要求:","en":"Scene requirements:"},
	"text_577":{"zh":"设置推荐内容类型","en":"Setting Recommendation Content Types"},
	"text_578":{"zh":"推荐","en":"Recommend"},
	"text_579":{"zh":"指定数据","en":"Specified data"},
	"text_580":{"zh":"行数","en":"Row number"},
	"text_581":{"zh":"列数","en":"Column number"},
	"text_582":{"zh":"页数","en":"The number of pages"},
	"text_583":{"zh":"海报尺寸","en":"Poster size"},
	"text_584":{"zh":"第","en":"The first"},
	"text_585":{"zh":"共","en":"common"},
	"text_586":{"zh":"全选","en":"All election"},
	"text_587":{"zh":"推荐算法","en":"Recommendation algorithm"},
	"text_588":{"zh":"内容来源","en":"Content source"},
	"text_589":{"zh":"添加资源","en":"Add resources"},
	"text_590":{"zh":"盒子","en":"Box"},
	"text_591":{"zh":"搜索中...","en":"Search..."},
	"text_592":{"zh":"无结果!","en":"No result!"},
	"text_593":{"zh":"该类颜色的频道不属于栏目用户组，不能添加","en":"Channels of this kind of color do not belong to the column user group and cannot be added."},
	"text_594":{"zh":"该类颜色的频道已经添加了","en":"Channels of this color have been added"},
	"text_595":{"zh":"获取已添加节目列表失败！","en":"Failed to get the added program list!"},
	"text_596":{"zh":"节目添加成功！","en":"Successful program addition!"},
	"text_597":{"zh":"请设置节目上架初始状态","en":"Please set the initial status of the program on the shelf"},
	"text_598":{"zh":"请正确设置定时上架时间！","en":"Please set the shelf time correctly!"},
	"text_599":{"zh":"失败的有：","en":"Failures include:"},
	"text_600":{"zh":"要添加的项有：","en":"The items to be added are:"},
	"text_601":{"zh":"添加成功！","en":"Add success!"},
	"text_602":{"zh":"节目","en":"program"},
	"text_603":{"zh":"未添加成功，原因是：","en":"No success was added because:"},
	"text_604":{"zh":"个资源未添加成功！","en":"A resource was not added successfully!"},
	"text_605":{"zh":"全部清空吗？","en":"Are they all empty?"},
	"text_606":{"zh":"添加资源：","en":"Add resources:"},
	"text_607":{"zh":"返回列表","en":"Return list"},
	"text_608":{"zh":"资源名称","en":"Resource name"},
	"text_609":{"zh":"库来源","en":"Sink source"},
	"text_610":{"zh":"关键字","en":"Keyword"},
	"text_611":{"zh":"平台","en":"platform"},
	"text_612":{"zh":"评分","en":"score"},
	"text_613":{"zh":"播放次数","en":"Frequency of play"},
	"text_614":{"zh":"发布人","en":"Publisher"},
	"text_615":{"zh":"已选条目:","en":"Selected entries:"},
	"text_616":{"zh":"空","en":"empty"},
	"text_617":{"zh":"portal路由","en":"Portal routing"},
	"text_618":{"zh":"Linux路由","en":"Linux routing"},
	"text_619":{"zh":"Android路由","en":"Android routing"},
	"text_620":{"zh":"场景列表","en":"Scene list"},
	"text_621":{"zh":"新建","en":"Newly build"},
	"text_622":{"zh":"场景id","en":"Scene ID"},
	"text_623":{"zh":"场景名称","en":"Scene name"},
	"text_624":{"zh":"场景要求","en":"Scenario requirements"},
	"text_625":{"zh":"场景节目列表","en":"List of Scene Programs"},
	"text_626":{"zh":"场景名称:","en":"Scenario Name:"},
	"text_627":{"zh":"人工指定情况列表","en":"Manual Specified Circumstances List"},
	"text_628":{"zh":"返回","en":"Return"},
	"text_629":{"zh":"推荐位","en":"Recommended bit"},
	"text_630":{"zh":"推荐要求","en":"Recommendation requirements"},
	"text_631":{"zh":"推荐节目名称","en":"Recommended Program Name"},
	"text_632":{"zh":"来源","en":"source"},
	"text_633":{"zh":"设置单元格类型","en":"Setting cell type"},
	"text_634":{"zh":".设置推荐算法","en":"Setting Recommendation Algorithms"},
	"text_635":{"zh":".设置内容类型","en":"Setting content type"},
	"text_636":{"zh":".设置内容来源","en":"Setting up content sources"},
	"text_637":{"zh":"提示","en":"Tips"},
	"text_638":{"zh":"确定提交此次修改？","en":"Determine to submit this revision?"},
	"text_639":{"zh":"确定对此分类要发布？","en":"Are you sure you want to publish this classification?"},
	"text_640":{"zh":"确定对此分类驳回发布","en":"Determine to reject publication of this classification"},
	"text_641":{"zh":"确定对此分类要重新发布","en":"Determine that this classification is to be reissued"},
	"text_642":{"zh":"确定删除当前编辑版本？","en":"Determine to delete the current edited version?"},
	"text_643":{"zh":"发布中...","en":"Release..."}}