var lang = {
    "text_0": { "zh": "新增portal", "en": "Add portal" },
    "text_1": { "zh": "portal名称", "en": "Portal name" },
    "text_2": { "zh": "portal类型", "en": "Portal type" },
    "text_3": { "zh": "普通版", "en": "Ordinary Edition" },
    "text_4": { "zh": "大事件", "en": "Big event" },
    "text_5": { "zh": "节日版", "en": "Holiday Edition" },
    "text_6": { "zh": "portal路径", "en": "Portal path" },
    "text_7": { "zh": "此处为通过配置文件修改,", "en": "Here it is modified by configuration file." },
    "text_8": { "zh": "若只改名称或描述，", "en": "If only the name or description is changed," },
    "text_9": { "zh": "则忽略不填", "en": "Ignore not to fill in" },
    "text_10": { "zh": "描述", "en": "describe" },
    "text_11": { "zh": "portal缩略图", "en": "Portal thumbnails" },
    "text_12": { "zh": "安卓缩略图url", "en": "Android thumbnail URL" },
    "text_13": { "zh": "若只改名称或描述，", "en": "If only the name or description is changed," },
    "text_14": { "zh": "则忽略不填", "en": "Ignore not to fill in" },
    "text_15": { "zh": "Portal风格", "en": "Portal style" },
    "text_16": { "zh": "保存", "en": "Preservation" },
    "text_17": { "zh": "新增风格", "en": "New style" },
    "text_18": { "zh": "风格名称", "en": "Style name" },
    "text_19": { "zh": "风格地址", "en": "Style address" },
    "text_20": { "zh": "缩略图地址", "en": "thumb" },
    "text_21": { "zh": "风格类型", "en": "Style type" },
    "text_22": { "zh": "适合角色", "en": "Suitable role" },
    "text_23": { "zh": "操作", "en": "operation" },
    "text_24": { "zh": "风格名称", "en": "Style name" },
    "text_25": { "zh": "请输入风格名称", "en": "Please enter a style name" },
    "text_26": { "zh": "风格地址", "en": "Style address" },
    "text_27": { "zh": "请输入风格地址", "en": "Please enter a style address" },
    "text_28": { "zh": "缩略图", "en": "thumbnail" },
    "text_29": { "zh": "请输入风格地址", "en": "Please enter a style address" },
    "text_30": { "zh": "风格类型", "en": "Style type" },
    "text_31": { "zh": "角色设置", "en": "Role setting" },
    "text_32": { "zh": "普通版", "en": "Ordinary Edition" },
    "text_33": { "zh": "用户属性版", "en": "User Attribute Edition" },
    "text_34": { "zh": "大事件版", "en": "Big event Edition" },
    "text_35": { "zh": "节日版", "en": "Holiday Edition" },
    "text_36": { "zh": "获取当前选中的id", "en": "Get the currently selected ID" },
    "text_37": { "zh": "有操作还没有保完成，", "en": "The operation is not guaranteed." },
    "text_38": { "zh": "请完成之后再新增", "en": "Please add it after completion." },
    "text_39": { "zh": "预览", "en": "preview" },
    "text_40": { "zh": "删除", "en": "delete" },
    "text_41": { "zh": "编辑", "en": "edit" },
    "text_42": { "zh": "风格名称不能为空!", "en": "Style name can not be empty!" },
    "text_43": { "zh": "风格地址不能为空!", "en": "Style address can not be empty!" },
    "text_44": { "zh": "请输入风格缩略图URL!", "en": "Please enter the style thumbnail URL!" },
    "text_45": { "zh": "全局赋值", "en": "Global assignment" },
    "text_46": { "zh": "图文上传路径", "en": "Text upload path" },
    "text_47": { "zh": "必须设置", "en": "Must set" },
    "text_48": { "zh": "必须设置", "en": "Must set" },
    "text_49": { "zh": "设置图片", "en": "Set pictures" },
    "text_50": { "zh": "服务器异常!", "en": "Server exception!" },
    "text_51": { "zh": "服务器异常!", "en": "Server exception!" },
    "text_52": { "zh": "若只改名称或描述，", "en": "If only the name or description is changed," },
    "text_53": { "zh": "则忽略不填", "en": "Ignore not to fill in" },
    "text_54": { "zh": "获取role", "en": "Get role" },
    "text_55": { "zh": "上层数据", "en": "Upper level data" },
    "text_56": { "zh": "预览", "en": "preview" },
    "text_57": { "zh": "删除", "en": "delete" },
    "text_58": { "zh": "编辑", "en": "edit" },
    "text_59": { "zh": "利用let", "en": "Using let" },
    "text_60": { "zh": "的特性完成闭包的功能", "en": "Features complete the function of closures" },
    "text_61": { "zh": "服务器异常", "en": "Server exception" },
    "text_62": { "zh": "有没有保存的操作，", "en": "Is there any saving operation?" },
    "text_63": { "zh": "请保存后再确定", "en": "Please save it and confirm it." },
    "text_64": { "zh": "将refresh", "en": "Will refresh" },
    "text_65": { "zh": "注册为全局", "en": "Register as Global" },
    "text_66": { "zh": "正则匹配,", "en": "Regular matching," },
    "text_67": { "zh": "匹配portal", "en": "Match portal" },
    "text_68": { "zh": "路径", "en": "Route" },
    "text_69": { "zh": "portal路径错误", "en": "Portal path error" },
    "text_70": { "zh": "portal名称错误", "en": "Portal name error" },
    "text_71": { "zh": "请输入portalurl", "en": "Please enter portalurl" },
    "text_72": { "zh": "内容包含敏感词", "en": "Content Contains Sensitive Words" },
    "text_73": { "zh": "服务器异常!", "en": "Server exception!" },
    "text_74": { "zh": "获取配置文件失败，", "en": "Failed to obtain configuration file." },
    "text_75": { "zh": "请检查portal", "en": "Please check portal" },
    "text_76": { "zh": "路径", "en": "Route" },
    "text_77": { "zh": "获取配置文件失败，", "en": "Failed to obtain configuration file." },
    "text_78": { "zh": "请检查portal", "en": "Please check portal" },
    "text_79": { "zh": "路径", "en": "Route" },
    "text_80": { "zh": "大事件、节日、用户属性版、普通版", "en": "Big Events, Festivals, User Attribute Edition, Common Edition" },
    "text_81": { "zh": "、", "en": "," },
    "text_82": { "zh": "、", "en": "," },
    "text_83": { "zh": "、", "en": "," },
    "text_84": { "zh": "内容包含敏感词", "en": "Content Contains Sensitive Words" },
    "text_85": { "zh": "服务器异常!", "en": "Server exception!" },
    "text_86": { "zh": "上传本地图片,", "en": "Upload local pictures." },
    "text_87": { "zh": "获取地址", "en": "Get address" },
    "text_88": { "zh": "图文上传路径", "en": "Text upload path" },
    "text_89": { "zh": "必须设置", "en": "Must set" },
    "text_90": { "zh": "必须设置", "en": "Must set" },
    "text_91": { "zh": "设置图片", "en": "Set pictures" },
    "text_92": { "zh": "服务器异常!", "en": "Server exception!" },
    "text_93": { "zh": "服务器异常!", "en": "Server exception!" }
}