var lang = {
	"text_0":{"zh":"新增portal","en":"Add portal"},
	"text_1":{"zh":"portal名称","en":"Portal name"},
	"text_2":{"zh":"portal类型","en":"Portal type"},
	"text_3":{"zh":"普通版","en":"Ordinary Edition"},
	"text_4":{"zh":"大事件","en":"Big event"},
	"text_5":{"zh":"节日版","en":"Holiday Edition"},
	"text_6":{"zh":"portal路径","en":"Portal path"},
	"text_7":{"zh":"此处为通过配置文件修改,若只改名称或描述，则忽略不填","en":"Here is to modify it through configuration file. If you only change the name or description, ignore not filling in."},
	"text_8":{"zh":"描述","en":"describe"},
	"text_9":{"zh":"portal缩略图","en":"Portal thumbnails"},
	"text_10":{"zh":"安卓缩略图url","en":"Android thumbnail URL"},
	"text_11":{"zh":"若只改名称或描述，则忽略不填","en":"If you change the name or description only, ignore not to fill in"},
	"text_12":{"zh":"Portal风格","en":"Portal style"},
	"text_13":{"zh":"保存","en":"Preservation"},
	"text_14":{"zh":"新增风格","en":"New style"},
	"text_15":{"zh":"请输入风格名称","en":"Please enter a style name"},
	"text_16":{"zh":"请输入风格地址","en":"Please enter a style address"},
	"text_17":{"zh":"用户属性版","en":"User Attribute Edition"},
	"text_18":{"zh":"大事件版","en":"Big event Edition"},
	"text_19":{"zh":"有操作还没有保完成，请完成之后再新增","en":"The operation is not guaranteed. Please add it after completion."},
	"text_20":{"zh":"预览","en":"preview"},
	"text_21":{"zh":"删除","en":"delete"},
	"text_22":{"zh":"编辑","en":"edit"},
	"text_23":{"zh":"风格名称不能为空!","en":"Style name can not be empty!"},
	"text_24":{"zh":"风格地址不能为空!","en":"Style address can not be empty!"},
	"text_25":{"zh":"请输入风格缩略图URL!","en":"Please enter the style thumbnail URL!"},
	"text_26":{"zh":"服务器异常!","en":"Server exception!"},
	"text_27":{"zh":"有没有保存的操作，请保存后再确定","en":"Do you have any saving operation? Please save it and confirm it later."},
	"text_28":{"zh":"请输入portalurl","en":"Please enter portalurl"},
	"text_29":{"zh":"用户组管理","en":"User Group Management"},
	"text_30":{"zh":"新建分组","en":"New grouping"},
	"text_31":{"zh":"添加成员","en":"Add member"},
	"text_32":{"zh":"查看成员","en":"View members"},
	"text_33":{"zh":"删除组","en":"delete group"},
	"text_34":{"zh":"导入用户组","en":"Import user groups"},
	"text_35":{"zh":"序号","en":"Serial number"},
	"text_36":{"zh":"组名称","en":"Group name"},
	"text_37":{"zh":"组信息","en":"Group information"},
	"text_38":{"zh":"操作","en":"operation"}}